//
// RequestModelC.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RequestModelC: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case value1 = "value1"
        case value2 = "value2"
        case value3 = "value3"
    }
    public var id: String
    public var type: ModelType
    public var key: String

    public init(id: String, type: ModelType, key: String) {
        self.id = id
        self.type = type
        self.key = key
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
        case key
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(type, forKey: .type)
        try container.encode(key, forKey: .key)
    }
}

