//
// RequestModelA.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RequestModelA: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case value1 = "value1"
        case value2 = "value2"
        case value3 = "value3"
    }
    public var id: String
    public var type: ModelType
    public var scope: String
    public var name: String
    public var description: String

    public init(id: String, type: ModelType, scope: String, name: String, description: String) {
        self.id = id
        self.type = type
        self.scope = scope
        self.name = name
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
        case scope
        case name
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(type, forKey: .type)
        try container.encode(scope, forKey: .scope)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
    }
}

