//
// V1EndpointPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum V1EndpointPostRequest: Codable, JSONEncodable, Hashable {
    case typeRequestModelA(RequestModelA)
    case typeRequestModelB(RequestModelB)
    case typeRequestModelC(RequestModelC)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeRequestModelA(let value):
            try container.encode(value)
        case .typeRequestModelB(let value):
            try container.encode(value)
        case .typeRequestModelC(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(RequestModelA.self) {
            self = .typeRequestModelA(value)
        } else if let value = try? container.decode(RequestModelB.self) {
            self = .typeRequestModelB(value)
        } else if let value = try? container.decode(RequestModelC.self) {
            self = .typeRequestModelC(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of V1EndpointPostRequest"))
        }
    }
}

